Repository AY2425S2-CS2103-F10-3/tp, pull requests merged in 2025-04, with the labels that each got.

#96 Update DG to include lesson delete use case
  docs/DeveloperGuide.md
Labels: type.Task, severity.High, alpha-bug

#95 Update User Guide to include lesson delete command details
  docs/UserGuide.md
Labels: type.Task, priority.High, alpha-bug

#97 Update storage file
  preferences.json
Labels: type.Task, severity.Low, alpha-bug

#98 Update sample data to remove duplicate timings
  src/main/java/seedu/tuitionbook/model/util/SampleDataUtil.java
Labels: type.Bug, severity.Low, alpha-bug

#99 Update parser to handle additional spacing when checking for duplicates and UG
  docs/UserGuide.md
  src/main/java/seedu/tuitionbook/logic/parser/ParserUtil.java
  src/test/java/seedu/tuitionbook/logic/parser/ParserUtilTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#102 Update notes about the add command in UG
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow, alpha-bug

#103 Update lesson-add success output
  src/main/java/seedu/tuitionbook/logic/commands/LessonAddCommand.java
  src/test/java/seedu/tuitionbook/logic/commands/LessonAddCommandTest.java
Labels: type.Bug, severity.Low, alpha-bug

#104 Branch update ug
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/tuitionbook/ui/HelpWindow.java
Labels: type.Task, severity.Low, alpha-bug

#105 Update developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low, alpha-bug

#107 Update UG summary and page title
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: type.Bug, severity.Medium, alpha-bug

#109 Update user guide command summary
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow, alpha-bug

#184 Fix documentation bugs
  docs/UserGuide.md
  src/main/java/seedu/tuitionbook/ui/HelpWindow.java
Labels: severity.VeryLow, type.DocumentationBug

#185 Fix Documentation Issues
  docs/DeveloperGuide.md
Labels: severity.VeryLow, type.DocumentationBug

#189 Delete preferences.json
  preferences.json
Labels: type.Task, priority.High

#188 Fix UserPref and UG
  docs/UserGuide.md
  docs/images/lessonWindow.png
  src/main/java/seedu/tuitionbook/commons/core/LogsCenter.java
  src/main/java/seedu/tuitionbook/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/tuitionbook/logic/LogicManagerTest.java
  src/test/java/seedu/tuitionbook/storage/JsonUserPrefsStorageTest.java
Labels: severity.VeryLow, type.DocumentationBug

#186 Fix documentation issues, and error message in Tag
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/tuitionbook/model/tag/Tag.java
Labels: severity.VeryLow, type.DocumentationBug

#192 Update ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.Low, type.DocumentationBug

#191 Fix links in DG and documentation bugs in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: severity.VeryLow, type.DocumentationBug

#193 Update ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.Low, type.DocumentationBug

#195 Fix bug in allow load duplicate lessons from json file
  src/main/java/seedu/tuitionbook/model/AddressBook.java
  src/main/java/seedu/tuitionbook/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/tuitionbook/testutil/TypicalPersons.java
Labels: severity.Medium, type.FunctionalityBug

#196 Update DG to include edit and find use case and more
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Low, type.DocumentationBug

#197 Update DG appendix and Help command message
  docs/DeveloperGuide.md
  src/main/java/seedu/tuitionbook/ui/HelpWindow.java
Labels: severity.Low, type.DocumentationBug

#199 Fix datetime bug
  src/main/java/seedu/tuitionbook/model/lesson/Lesson.java
Labels: severity.Low, type.FunctionalityBug

#202 Add planned enhancements to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/tuitionbook/ui/HelpWindow.java
Labels: severity.VeryLow, type.PossibleEnhancement

#203 Update Ui.png
  docs/images/Ui.png
Labels: type.Story, priority.High

#204 Update aboutus.md and Developer Guide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/zerolegacy.png
Labels: type.Story, priority.Low

#207 Update saving data part to clarify corrupted data file
  docs/UserGuide.md
Labels: type.Task, priority.High
