Repository AY2425S2-CS2103-F10-3/tp, pull requests merged in 2025-03, with the labels that each got.

#10 Add Bryon's photo
  docs/images/bryonk.png
Labels: type.Task

#11 Add Roy's photo
  docs/images/rt0118.png
Labels: type.Task

#14 Add Dextor's photo
  docs/images/zerolegacy.png
Labels: type.Task

#13 Update teams page to add RT0118's information
  docs/AboutUs.md
  docs/team/rt0118.md
Labels: type.Task

#12 Update teams page to add Bryon's info
  docs/AboutUs.md
  docs/team/bryonk.md
Labels: type.Task

#15 Update teams page with Dextor's info
  docs/AboutUs.md
  docs/team/zerolegacy.md
Labels: type.Task

#17 Update README, jekyll config and DG
  README.md
  docs/DeveloperGuide.md
  docs/_config.yml
  docs/index.md
Labels: type.Task

#20 Fix typo in Dextor's aboutus.md
  docs/AboutUs.md
  docs/images/Ui.png
Labels: type.Bug

#22 Add Lesson class to TuitionBook
  codecov.yml
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#24 Update Add command to handle Lessons
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
Labels: type.Task, priority.High

#26 Branch list lessons
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High

#33 Update DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium

#35 Branch update help page
  src/main/java/seedu/tuitionbook/logic/commands/AddCommand.java
  src/main/java/seedu/tuitionbook/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, type.Task, priority.Medium

#37 Update user guide to fix add command mistake
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Medium

#39 Update message format to include lesson details
  src/main/java/seedu/tuitionbook/logic/Messages.java
  src/main/java/seedu/tuitionbook/model/util/SampleDataUtil.java
Labels: type.Bug, severity.VeryLow

#41 Fix bug in PersonCard
  src/main/java/seedu/tuitionbook/ui/PersonCard.java
  src/test/java/seedu/tuitionbook/testutil/PersonUtil.java
Labels: type.Bug, severity.Low

#43 Add note in User Guide to inform user of list command scenarios
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#51 Fix application title
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.VeryLow

#55 Update build.gradle to enable assertions
  build.gradle
Labels: type.Task, priority.High

#52 Fix naming issue in help command
  src/main/java/seedu/tuitionbook/ui/HelpWindow.java
Labels: type.Bug, severity.VeryLow

#58 Update help page to include new lesson features
  src/main/java/seedu/tuitionbook/ui/HelpWindow.java
Labels: type.Task, priority.Low, severity.Low

#54 Branch lesson delete command
  src/main/java/seedu/tuitionbook/logic/commands/LessonDeleteCommand.java
  src/main/java/seedu/tuitionbook/logic/parser/AddressBookParser.java
  src/main/java/seedu/tuitionbook/logic/parser/LessonDeleteCommandParser.java
  src/test/java/seedu/tuitionbook/logic/commands/LessonDeleteCommandTest.java
  src/test/java/seedu/tuitionbook/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/tuitionbook/logic/parser/LessonDeleteCommandParserTest.java
Labels: type.Story, priority.High

#48 Branch list lessons
  docs/DeveloperGuide.md
  src/main/java/seedu/tuitionbook/logic/commands/CommandResult.java
  src/main/java/seedu/tuitionbook/logic/commands/LessonListCommand.java
  src/main/java/seedu/tuitionbook/logic/parser/AddressBookParser.java
  src/main/java/seedu/tuitionbook/logic/parser/LessonListCommandParser.java
  src/main/java/seedu/tuitionbook/ui/LessonWindow.java
  src/main/java/seedu/tuitionbook/ui/MainWindow.java
  src/main/resources/view/LessonWindow.css
  src/main/resources/view/LessonWindow.fxml
  src/test/java/seedu/tuitionbook/logic/commands/CommandResultTest.java
  src/test/java/seedu/tuitionbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/tuitionbook/logic/commands/LessonListCommandTest.java
  src/test/java/seedu/tuitionbook/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/tuitionbook/logic/parser/LessonListCommandParserTest.java
Labels: type.Story, priority.High

#56 Branch add lessonadd feature
  src/main/java/seedu/tuitionbook/logic/commands/LessonAddCommand.java
  src/main/java/seedu/tuitionbook/logic/parser/AddressBookParser.java
  src/main/java/seedu/tuitionbook/logic/parser/LessonAddCommandParser.java
  src/test/java/seedu/tuitionbook/logic/commands/LessonAddCommandTest.java
  src/test/java/seedu/tuitionbook/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/tuitionbook/logic/parser/LessonAddCommandParserTest.java
Labels: type.Story, priority.High

#63 Update help message to include lesson-list command
  src/main/java/seedu/tuitionbook/ui/HelpWindow.java
Labels: type.Task, priority.Medium

#64 Fix lesson delete command
  src/main/java/seedu/tuitionbook/logic/commands/LessonDeleteCommand.java
Labels: type.Bug, priority.High, severity.High

#68 Update DG and add LessonAddSequence uml diagram
  docs/DeveloperGuide.md
  docs/diagrams/LessonAddSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/LessonAddSequenceDiagram.png
Labels: type.Task

#67 Update uml files in DG
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Task
